# $FreeBSD$

compute_engine_instance:
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-0-release-amd64
  cpu: 8
  memory: 8G
  disk: 40

task:
  name: Build aquaBSD kernel for 'amd64' target
  env:
    TARGET: amd64
    TARGET_ARCH: amd64
  timeout_in: 120m
  setup_script:
  - uname -a
  - df -h
  - pkg --version
  - mkdir -p /usr/obj/$(pwd -P)
  kernel_build_script:
  - make -j$(sysctl -n hw.ncpu) WITHOUT_TOOLCHAIN=yes WITHOUT_LIB32=yes WITHOUT_TCSH=yes WITHOUT_FREEBSD_UPDATE=yes WITHOUT_PORTSNAP=yes WITHOUT_SENDMAIL=yes WITHOUT_TCP_WRAPPERS=yes WITHOUT_PAM_SUPPORT=yes WITHOUT_VT=yes WITHOUT_SVNLITE=yes WITHOUT_RESCUE=yes buildkernel
  distribute_script:
  - mkdir -p /usr/obj/$(pwd -P)/amd64.amd64/release/dist/
  - make DISTDIR=/usr/obj/$(pwd -P)/amd64.amd64/release/dist/ -DNO_ROOT distributekernel
  package_script:
  - make packagekernel DISTDIR=/usr/obj/$(pwd -P)/amd64.amd64/release/dist/
  - mkdir .build/
  - mv /usr/obj/$(pwd -P)/amd64.amd64/release/dist/kernel.txz .build/
  post_script:
  - ls -l .build/
  - df -h
  - du -h -s /usr/obj
  distribution_artifacts:
    path: ".build/*"